[package]
name = "walls-bot-rs"
version = "0.1.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"

[dependencies]
teloxide = "0.1.0"
futures = "0.3.4"
tokio = "0.2.11"
log = "0.4.8"
pretty_env_logger = "0.4.0"
rand = "0.7.3"
lazy_static = "1.4.0"
walkdir = "2.3.1"
