[package]
name = "linkleaner"
version = "1.5.2"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Telegram bot that replaces social media links to enhance their previews"
keywords = ["telegram", "bot"]
repository = "https://github.com/msfjarvis/linkleaner"
homepage = "https://github.com/msfjarvis/linkleaner"
readme = "README.md"
include = ["src/**/*", "LICENSE-*", "README.md"]
publish = false

[features]
default = ["ddinstagram"]
console = ["console-subscriber"]
ddinstagram = []
journald = ["tracing-journald"]

[dependencies]
console-subscriber = { version = "0.1.9", optional = true }
dotenvy = "0.15.7"
futures = "*"
once_cell = "1.17.1"
regex = "1.8.1"
reqwest = { version = "*", default-features = false, features = ["json", "rustls-tls"] }
serde = "*"
serde_derive = "*"
serde_json = "*"
teloxide = { version = "0.12.2", features = ["auto-send", "cache-me", "ctrlc_handler", "macros", "rustls"], default-features = false }
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-journald = { version = "0.3.0", optional = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
