[package]
name = "walls-bot-rs"
version = "0.17.2"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2021"
license = "MIT/Apache-2.0"
description = "Telegram bot that scans a local filesystem for images and sends them to Telegram when commands are issued."
keywords = ["telegram", "bot"]
repository = "https://github.com/msfjarvis/walls-bot-rs"
homepage = "https://github.com/msfjarvis/walls-bot-rs"
readme = "README.md"
include = ["src/**/*", "LICENSE-*", "README.md"]
publish = false

[package.metadata.deb]
extended-description = "Telegram bot that scans a local filesystem for images and sends them to Telegram when commands are issued."
features = ["console", "journald"]
priority = "optional"
depends = "$auto"
maintainer-scripts = "pkg/debian/"
systemd-units = { enable = true }

[features]
console = ["console-subscriber"]
journald = ["tracing-journald"]

[dependencies]
console-subscriber = { version = "0.1.8", optional = true }
dotenvy = "0.15.3"
fastrand = "1.8.0"
futures = "*"
imagesize = "0.10.0"
once_cell = "1.14.0"
regex = "1.6.0"
reqwest = { version = "*", default-features = false, features = ["json", "rustls-tls"] }
seahash = "4.1.0"
serde = "*"
serde_derive = "*"
serde_json = "*"
sled = "0.34.7"
teloxide = { version = "0.10.1", features = ["auto-send", "cache-me", "ctrlc_handler", "macros", "rustls"], default-features = false }
tokio = { version = "1.21.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.36"
tracing-journald = { version = "0.3.0", optional = true }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
walkdir = "2.3.2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
