[package]
name = "walls-bot-rs"
version = "0.2.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Telegram bot that scans a local filesystem for images and sends them to Telegram when commands are issued."
keywords = ["telegram", "bot"]
repository = "https://github.com/msfjarvis/walls-bot-rs"
homepage = "https://github.com/msfjarvis/walls-bot-rs"
readme = "README.md"

[package.metadata.deb]
extended-description = "Telegram bot that scans a local filesystem for images and sends them to Telegram when commands are issued."
priority = "optional"
depends = "$auto"

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
rand = "0.8.3"
teloxide = { version = "0.4.0", features = ["macros", "auto-send"] }
tokio = { version = "1.5.0", features = ["rt-multi-thread", "macros"] }
walkdir = "2.3.2"

[patch.crates-io]
teloxide-core = { git = "https://github.com/teloxide/teloxide-core", rev = "e8ca6a84455ecdabce26a0b8ae1fb9d3a8308808" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
